### ISSUE TITLE
feat: Pop-up HTML, CSS

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-G/Othello#10]
- [x] 適切な名前でdevelopからブランチを切る
- [x] src/components/PopUp.vueを作成
- [x] HTML作成

**Comment by Tucker263** [comment]
コンポーネントの実行結果はどう確認すれば、よろしいでしょうか？

**Comment by mcnLeandro** [comment]
本来はrouterを設定してもらうところまでやって欲しかったんですが、routerの設定が終わっていないので、

`App.vue` をにコンポーネントを挿入して確認してください！
コンポーネントの使い方は以下を参照してください！

https://jp.vuejs.org/v2/guide/components.html
