### ISSUE TITLE
feat: フォーマッターの追加

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-G/Othello#11]
フォーマッターとしてprettierを追加しようと思います。

自分の設定はこんな感じです。
```
{
  "tabWidth": 4,
  "semi": true,
  "singleQuote": true
}
````
- インデントサイズ4
- セミコロンつける;
- " " でなく ' ' を使う
@m2mt-l 
@kuro1221 
@Tucker263 

問題ないでしょうか？？？
問題なければ追加します！

**Comment by Tucker263** [comment]
フォーマッターとprettierとはどういうものですか？

**Comment by mcnLeandro** [comment]
コードをきれいに整えてくれるものです！
チーム開発ではコードの統一感を得ることが難しいので、フォーマッターを用意してコードの書き方を統一します！

**Comment by Tucker263** [comment]
わかりました！
ありがとうございます！

**Comment by kuro1221** [comment]
Prettierの追加ありだと思います！

**Comment by mcnLeandro** [comment]
@kuro1221 
https://reffect.co.jp/vue/eslint#ESLint_Prettier
こちら参考にしてください！
