### ISSUE TITLE
feat: Board LinkedList Module

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-G/Othello#38]
https://discord.com/channels/684232065423900721/901689311114719242/906751832515293296
https://discord.com/channels/684232065423900721/901689311114719242/906778228994244609
https://discord.com/channels/684232065423900721/901689311114719242/906801649564147712

Board受け取る、もしくは作成して、それぞれのSquareの上下左右斜めの関係を元に連結します。
これでコードの可読性を高めることが目的です。
ちょっと提案しただけですが、やってみる価値はあると思ったので、新しいタスクに入れてみました！

- [x] #26 
- [x] Squareモデルにメンバ変数追加 8方向
- [x] モジュール名を決める(BoardList ? SquaresList? or else ..)
- [x] モジュール作成

わからないところあれば言ってください！

**Comment by mcnLeandro** [comment]
- Squareを格納した二次元配列を作成するメソッド.(完成したやつをメンバ変数にセットしてもOK)
- 作成された二次元配列を使って、Squareの8方向を連結するメソッド

**Comment by mcnLeandro** [comment]
x,y

**Comment by mcnLeandro** [comment]
```js
class ? {
  private suquares: Square[][] | null = []
  
  set
  get
 
  static createBoard() : Square{
  }
}
```

**Comment by mcnLeandro** [comment]
```js
const board = new BoardMaker(size)
const board = BoardMaker.create(size)
```

**Comment by Tucker263** [comment]
質問なのですが、board.tsとboardLinkedListModuleは何が違うのでしょうか？

**Comment by mcnLeandro** [comment]
BoardはSquares[][]をただ格納するためのモデルです。
BoardinkedListはSquare[][] を作成して、Boardのインスタンスをを作成するメソッドを持つモジュールです。
Board.tsはモデルなのでメソッドを持つことができません。なのでモジュールを介して作成します。

**Comment by Tucker263** [comment]
わかりました！
ありがとうございます！
