### ISSUE TITLE
クローンしてローカルに開発環境準備

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-G/Othello#4]
m2mtさんが環境構築してくれたので、クローンしてローカル、docker、もしくは仮想環境を使って開発環境を準備してください！

終わったらチェックをつけてください！

- [x] @m2mt-l 
- [x] @mcnLeandro 
- [x] @Tucker263 
- [x] @kuro1221

**Comment by mcnLeandro** [comment]
自分はローカル環境にそのままクローンしちゃいました笑笑

```shell
$ git clone git@github.com:Recursion-Group-G/Othello.git
$ cd Othello
$ yarn install
$ yarn serve
```
でOKですね！

**Comment by Tucker263** [comment]
Leandroさんの方法で試してみたのですが、yarn installがうまくいきませんでした。
少し原因を調べてみます。

**Comment by Tucker263** [comment]
Leandroさんの方法で環境構築をしようとしたのですが、yarn installがうまくいきませんでした。
少し原因を調べてみます。

**Comment by m2mt-l** [comment]
この環境はnpmの方で作っているので、たぶんnpm installならうまくいくと思います！なぜLeandroさんがyarnで動いたのかが逆に謎です笑

**Comment by Tucker263** [comment]
npm installを試して、うまくいきました！
しかし、npm run serveがうまくいかないです。

**Comment by m2mt-l** [comment]
一歩進みましたね！
npm install -g @vue/cliでVue CLIはインストールしてますかね？あとはcdでディレクトリを移動していないとか。

**Comment by mcnLeandro** [comment]
🚀
