### ISSUE TITLE
feat: Game HTML,CSS

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-G/Othello#9]
- [ ] 適切な名前でdevelopからブランチを切る
- [ ] src/views/Game.vueの作成
- [ ] HTMLの作成

**Comment by m2mt-l** [comment]
表示させるのにmain.tsを適当に書き換えたり、すでにconfig.tsを作りたくなってしまったので作成しつつやってるのですが、ここらへん含んでpushしてしまって大丈夫なんでしょうか？

**Comment by mcnLeandro** [comment]
@m2mt-l 
返信遅れてすみません！
できる限りレイアウトだけを作成して欲しいのですが、
レイアウト作成するために必要なのであれば全然問題ないです！

**Comment by m2mt-l** [comment]
かなりハードコーディングっぽくなるのでconfig.tsで値を取得しようとしてました。一旦dataに入れておきます！コメント入れます！
